global:
  environment: dev
  project: aiops
  region: ap-south-1

registry: 350480401763.dkr.ecr.ap-south-1.amazonaws.com

frontend:
  enabled: true
  image:
    repository: 350480401763.dkr.ecr.ap-south-1.amazonaws.com/aiops-dev-frontend
    tag: latest
    pullPolicy: Always
  replicas: 1

api:
  enabled: true
  image:
    repository: 350480401763.dkr.ecr.ap-south-1.amazonaws.com/aiops-dev-api
    tag: latest
    pullPolicy: Always
  replicas: 1

db:
  enabled: true
  replicas: 1
  storage: 5Gi