# Global values
global:
  environment: dev
  project: aiops
  region: ap-south-1

# ECR registry
registry: 350480401763.dkr.ecr.ap-south-1.amazonaws.com

# Frontend service
frontend:
  enabled: true
  image:
    repository: 350480401763.dkr.ecr.ap-south-1.amazonaws.com/aiops-dev-frontend
    tag: latest
    pullPolicy: Always
  replicas: 1

# API service
api:
  enabled: true
  image:
    repository: 350480401763.dkr.ecr.ap-south-1.amazonaws.com/aiops-dev-api
    tag: latest
    pullPolicy: Always
  replicas: 1

# Database
db:
  enabled: true
  replicas: 1