apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    project: aiops
spec:
  project: sre-platform

  source:
    repoURL: https://github.com/amansinha24/aiops-sre-platform
    targetRevision: main
    path: observability/prometheus

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    syncOptions:
      - CreateNamespace=false

  revisionHistoryLimit: 5