apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: application
type: Opaque
stringData:
  DB_HOST: db-service
  DB_PORT: "5432"
  DB_NAME: aiops
  DB_USER: aiops
  DB_PASSWORD: aiops123
  POSTGRES_DB: aiops
  POSTGRES_USER: aiops
  POSTGRES_PASSWORD: aiops123